name: "HidePlayers"
version: "${version}"
main: "me.rafaelka.hideplayers.HidePlayersPlugin"
api-version: "1.20"
softdepend: [ "PlaceholderAPI" ]
author: "Rafaelka"

commands:
  visibility:
    description: "Main plugin command"

permissions:
  # Super permission
  hideplayers.admin:
    description: "Admin permission to access all plugin features"
    default: op
    children:
      - "hideplayers.command.reload"
      - "hideplayers.command.toggle"
  # /visibility reload
  hideplayers.command.reload:
    description: "Allows to reload plugin configurations and cache"
    default: op
  # /visibility toggle
  hideplayers.command.toggle:
    description: "Allows to toggle players visibility"
    default: true
